### PR TITLE
ci: Change the system tests distribution to speed up the run and work…

### PR DESCRIPTION
**Pull request by jgsbennett**
…around a vega issue that manifests late in one of the long run.

### CODE REVIEW

**Comment by jgsbennett** [comment]
https://jenkins.vega.rocks/job/common/job/system-tests/4197/

**Comment by jgsbennett** [comment]
https://jenkins.vega.rocks/job/common/job/system-tests/4219/

**Comment by jgsbennett** [comment]
https://jenkins.vega.rocks/job/common/job/system-tests/4262/

**Comment by jgsbennett** [comment]
Running against Paul's full_fixes_11 branch, which includes the fix for the latest OOM error:
https://jenkins.vega.rocks/job/common/job/system-tests/4284/

**Comment by jgsbennett** [comment]
And another with my change to limit the number of workers globally, better.
https://jenkins.vega.rocks/job/common/job/system-tests/4296/

**Comment by jgsbennett** [comment]
Experiment to see how long this subjob is:
https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/21790/

**Comment by jgsbennett** [comment]
Try the full run again with a different set:
https://jenkins.vega.rocks/job/common/job/system-tests/4367/

**Review by fkondej — APPROVED** [review]

**Review by daniel1302 — APPROVED** [review]

**Pull request merged**
